import React from 'react';
import Header from '@/components/common/Header';
import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="kr">
      <body className={inter.className}>
        <div id="wrap">
          <div id="mobile" className="bg-gray-100">
            <Header />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
